service: sge-lambda
provider:
  name: aws
  runtime: nodejs18.x
  environment:
   
functions:
  app:
    handler: index.handler
    events:
      - http: # this is an API Gateway HTTP event trigger
          path: /
          method: ANY
          cors: true
      - http: # all routes get proxied to the Express router
          path: /{proxy+}
          method: ANY
          cors: true