const constants={

// Table Names
CLIET_TABLE:"MUANAKU_CLIET",
CHIKEN_BATCH_TABLE:"MUANAKU_CHIKEN_BATCH",
ORDER_TABLE:"MUANAKU_ORDER",
USER_TABLE:"MUANAKU_USER",
INCIDENTS_TABLE:"MUANAKU_INCIDENTS",
VACINE_TABLE:"MUANAKU_VACINE",
ANOMALIES_TABLE:"MUANAKU_ANOMALIES",
SUCURSAL_TABLE:"MUANAKU_SUCURSAL",
SMS_TABLE:"MUANAKU_SMS",
PROFILE_TABLE:"MUANAKU_PROFILE",
COST_TABLE:"MUANAKU_COST",
FEED_PREVISION_TABLE:"MUANAKU_FEED_PREVISION",
PRICE_CONFIG_TABLE:"MUANAKU_PRICE_CONFIG",
LOGININFO_TABLE:"MUANAKU_LOGININFO",
}

module.exports=constants;